name: Extract OpenFront Data

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to extract (YYYYMMDD), e.g. 20250715'
        required: false
        default: ''

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history so we can manage branches
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm i

      - name: Set DATE environment variable
        run: |
          if [ -z "${{ github.event.inputs.date }}" ]; then
            echo "DATE=$(date -u -d 'yesterday' +%Y%m%d)" >> $GITHUB_ENV
          else
            echo "DATE=${{ github.event.inputs.date }}" >> $GITHUB_ENV
          fi
      
      - name: Run extractor
        run: node extract.js
        
      - name: Switch to or create gh-pages branch
        run: |
          git fetch origin gh-pages || true
          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git reset --hard
          fi

      - name: Move JSON data to gh-pages
        run: |
          rm -rf json
          cp -r ../json ./  # Assumes extract.js outputs to ./json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add json/*.json
          git diff --cached --quiet && echo "No changes to commit" && exit 0

          git commit -m "Update openfront JSON for $DATE"
          git push origin gh-pages
