name: Extract and Publish OpenFront Data

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to extract (YYYYMMDD), e.g. 20250715'
        required: false
        default: ''

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
          
      - name: Install dependencies
        run: npm i

      - name: Set DATE environment variable
        run: |
          if [ -z "${{ github.event.inputs.date }}" ]; then
            echo "DATE=$(date -u -d 'yesterday' +%Y%m%d)" >> $GITHUB_ENV
          else
            echo "DATE=${{ github.event.inputs.date }}" >> $GITHUB_ENV
          fi

      - name: Run extractor script
        run: node extract.js

      - name: Upload json/ to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./json
          destination_dir: json

